server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: api-movie
  zipkin:
    base-url: http://zipkin-service:9411/
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: api-movie
    description: Movies
