server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:

  data:
    mongodb:
      database: series-dev
      port: 27017
      host: localhost  
      
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: api-serie
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
    
    
    
    
    
